---
name: R

on:
  release:

permissions: {}

jobs:
  r:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Debug
        uses: raven-actions/debug@9dbdeb7eea607a7d73411895c65987e71d59a466 # v1.2.0
